# Event logs para Spark History Server local del proyecto.
spark.eventLog.enabled           true
spark.eventLog.dir               file:/opt/spark-events
spark.history.fs.logDirectory    file:/opt/spark-events
spark.history.fs.update.interval 10s
